import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NuqsAdapter>
          <SidebarProvider>
            <AppSidebar />
            <main className="p-2">
              <SidebarTrigger className="sticky top-2 z-50" />
              {children}
            </main>
          </SidebarProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
