import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cookies } from "next/headers";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import ThemeToggle from "@/components/theme-toggle"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AppFrame({
  children,
  defaultOpen,
}: Readonly<{
  children: React.ReactNode;
  defaultOpen?: boolean;
}>) {
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar />
      <SidebarInset className="p-2">
        <div className="sticky top-2 z-50 flex items-center justify-between gap-2">
          <SidebarTrigger className="h-8 w-8" />
          <ThemeToggle />
        </div>
        {children}
      </SidebarInset>
    </SidebarProvider>
  )
}

async function AppFrameWithCookie({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value !== "false"

  return <AppFrame defaultOpen={defaultOpen}>{children}</AppFrame>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NuqsAdapter>
          <Suspense fallback={null}>
            <AppFrameWithCookie>{children}</AppFrameWithCookie>
          </Suspense>
        </NuqsAdapter>
      </body>
    </html>
  );
}
